# tasks file for role_docker_compose
- block:
    - name: Download the docker-compose archive
      shell: sudo curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

    - name: Ensure that the binary docker-compose can be executed
      file:
        path: /usr/local/bin/docker-compose
        mode: u+x 

    - name: Ensure that symbolik link /usr/local/bin/docker-compose to /usr/local/bin/docker-compose is well present
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Register docker-composer version
      shell: "docker-compose --version"
      register: docker_composer_version

    - debug: 
        var: docker_composer_version

    - name: Ensure the version of docker compose
      assert:
       that: 
        # - docker-composer-version in "docker-compose version 1.24.1, build 4667896b" 
         - docker_composer_version.stdout in "docker-compose version 1.24.1, build 4667896b"
  become: yes
